# Generated by Django 6.0.1 on 2026-02-06 16:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("policy_number", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateField(help_text="Policy start date")),
                ("end_date", models.DateField(help_text="Policy expiry date")),
                (
                    "policy_document_url",
                    models.URLField(
                        help_text="Supabase Storage public URL for policy PDF/Image",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Admin provides reason if policy is rejected",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "policies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "dob",
                    models.DateField(blank=True, help_text="Date of birth", null=True),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("parent", "Parent"),
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("son", "Son"),
                            ("daughter", "Daughter"),
                        ],
                        help_text="Relation to policy holder",
                        max_length=20,
                    ),
                ),
                (
                    "is_minor",
                    models.BooleanField(
                        default=False, help_text="Automatically set based on age"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        help_text="All family members belong to one policy",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to="api.policy",
                    ),
                ),
            ],
            options={
                "db_table": "family_members",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "claim_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="users.user",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        db_column="policy_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="api.policy",
                    ),
                ),
            ],
            options={
                "db_table": "claims",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PAN", "PAN Card"),
                            ("AADHAAR", "Aadhaar Card"),
                            ("HOSPITAL_BILL", "Hospital Bill"),
                            ("PHARMACY_BILL", "Pharmacy Bill"),
                            ("POLICY", "Policy Document"),
                        ],
                        default="POLICY",
                        help_text="Type of document uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "belongs_to_relation",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("father", "Father"),
                            ("mother", "Mother"),
                        ],
                        default="self",
                        help_text="Whose document this is - self, father, or mother",
                        max_length=10,
                    ),
                ),
                (
                    "bucket_name",
                    models.CharField(
                        default="policies",
                        help_text="Supabase Storage bucket name",
                        max_length=100,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path in Supabase Storage", max_length=500
                    ),
                ),
                ("file_size", models.IntegerField(help_text="Size in bytes")),
                (
                    "content_type",
                    models.CharField(help_text="MIME type", max_length=100),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family_member",
                    models.ForeignKey(
                        blank=True,
                        db_column="family_member_id",
                        help_text="The family member this document belongs to (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="api.familymember",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        db_column="policy_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="api.policy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_documents",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "policy_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimDocument",
            fields=[
                (
                    "document_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("hospital_bill", "Hospital Bill"),
                            ("pharmacy_bill", "Pharmacy Bill"),
                            ("aadhaar", "Aadhaar Card"),
                            ("pan", "PAN Card"),
                        ],
                        help_text="Type of document - determines bucket and extractor to use",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.TextField(help_text="Path inside Supabase Storage bucket"),
                ),
                (
                    "file_url",
                    models.URLField(
                        help_text="Public or signed URL for the document",
                        max_length=1000,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        db_column="claim_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="api.claim",
                    ),
                ),
            ],
            options={
                "db_table": "claim_documents",
                "ordering": ["-uploaded_at"],
                "unique_together": {("claim", "document_type")},
            },
        ),
        migrations.CreateModel(
            name="ClaimExtractedField",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("hospital_bill", "Hospital Bill"),
                            ("pharmacy_bill", "Pharmacy Bill"),
                            ("aadhaar", "Aadhaar Card"),
                            ("pan", "PAN Card"),
                        ],
                        help_text="Document type - same as bucket name",
                        max_length=20,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Name of the extracted field (e.g., 'patient_name', 'amount')",
                        max_length=100,
                    ),
                ),
                (
                    "field_value",
                    models.TextField(help_text="Extracted value from the document"),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence score between 0.00 and 1.00",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        db_column="claim_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_fields",
                        to="api.claim",
                    ),
                ),
            ],
            options={
                "db_table": "claim_extracted_fields",
                "ordering": ["-created_at"],
                "unique_together": {("claim", "document_type", "field_name")},
            },
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(fields=["user"], name="policies_user_id_b9f778_idx"),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(fields=["status"], name="policies_status_d09338_idx"),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["policy_number"], name="policies_policy__ca1bbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familymember",
            index=models.Index(
                fields=["policy"], name="family_memb_policy__4a97a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familymember",
            index=models.Index(
                fields=["relation"], name="family_memb_relatio_ca661c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="familymember",
            unique_together={("policy", "name", "dob", "relation")},
        ),
        migrations.AddIndex(
            model_name="policydocument",
            index=models.Index(
                fields=["user", "document_type"], name="policy_docu_user_id_528ec4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policydocument",
            index=models.Index(
                fields=["policy", "family_member"],
                name="policy_docu_policy__6d195e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policydocument",
            index=models.Index(
                fields=["document_type", "belongs_to_relation"],
                name="policy_docu_documen_1e2c1b_idx",
            ),
        ),
    ]
