# Generated by Django 6.0.1 on 2026-02-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_missing_columns_to_policy_documents"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("hospital_bill", "Hospital Bill"),
                    ("pharmacy_bill", "Pharmacy Bill"),
                    ("aadhaar", "Aadhaar Card"),
                    ("pan", "PAN Card"),
                    ("birth_certificate", "Birth Certificate"),
                ],
                help_text="Type of document - determines bucket and extractor to use",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="claimextractedfield",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("hospital_bill", "Hospital Bill"),
                    ("pharmacy_bill", "Pharmacy Bill"),
                    ("aadhaar", "Aadhaar Card"),
                    ("pan", "PAN Card"),
                    ("birth_certificate", "Birth Certificate"),
                ],
                help_text="Document type - same as bucket name",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="policydocument",
            name="content_type",
            field=models.CharField(help_text="MIME type", max_length=100),
        ),
        migrations.AlterField(
            model_name="policydocument",
            name="file_size",
            field=models.IntegerField(help_text="Size in bytes"),
        ),
        migrations.AlterField(
            model_name="policydocument",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="policydocument",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_documents",
                to="users.user",
            ),
        ),
    ]
