# Generated by Django 6.0.1 on 2026-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "supabase_user_id",
                    models.UUIDField(blank=True, db_index=True, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin")],
                        db_index=True,
                        default="user",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                    models.Index(fields=["role"], name="users_role_0ace22_idx"),
                    models.Index(
                        fields=["supabase_user_id"], name="users_supabas_e2a624_idx"
                    ),
                ],
            },
        ),
    ]
